home:
    path: /
    controller: App\Controller\HomeController::index

articles_list:
    path: /articles
    controller: App\Controller\ArticlesController::list

articles_list_category:
    path: /articles/category/{slug}
    controller: App\Controller\ArticlesController::listCategory

articles_show:
    path: /articles/{slug}
    controller: App\Controller\ArticlesController::show

articles_show_old:
    path: /article/{id}
    controller: App\Controller\ArticlesController::showOld

calendar:
    path: /calendar
    controller: App\Controller\CalendarController::index

contacts:
    path: /contacts
    controller: App\Controller\ContactsController::index